### PR TITLE
Add 0003 Hiring Grades, from Bad to Excellent

### PR DESCRIPTION
**Pull request by alexykot**
Description of personality qualities required to match the human quality grades. Required for effective hiring.

Also proposing to change `Phenomenal` to `Excellent` as less open to interpretation.

### CODE REVIEW

**Comment by nirth** [comment]
Thanks for the effort :) It is nicely written FYD! But I'm going to reject it -  I'm actually highly opposed to this HR practice of grading people and storing the grade for people. In my opinion, it's extremely important to make sure that when people critique something, they critic work (ideas, implementation, products), but never people. The team should be incentivised to critique the quality of code, without being afraid to harm feelings.

Like here - in my experience grading people nurtures an environment that's less productive than an environment where people grade work. In other words, on the meeting - any team member should be able to say something along the lines of "This is the stupidest idea I heard in last 10 years" - without long term consequences to the person proposing the idea, there could be awkwardness in short term.

**Comment by nirth** [comment]
I'm also not sure why would one keep the `Ok` people. In my experience, I have a value calculation – Each person delivers negative or positive value to the project, for example:

1. Person is too junior in a given tech stack:
A. But has experience and domain knowledge - Strategically promising to deliver a lot of value, consider keeping them.
B. Doesn't have domain knowledge - They take too much time from their fellow colleagues on explanation, without delivering - transferring to a different type of job where they have technical and /or domain expertise, or letting them go.

1. A person is good but too expensive:
A. Can I hire 2.5 equally good people for the same money? Then I could let them go.
B. No, I can't. Then keep them.

**Comment by nirth** [comment]
Could you reformat change to FyD-2 as separate pull request, I'll merge it.

**Comment by alexykot** [comment]
> HR practice of grading people and storing the grade

I don't think this PR is says anything about HR or storing the grades anywhere. That's not what this text is about. 

I think there is plenty of value in having a common written idea of what a "Great" personality looks like vs an "Okay" one without relying solely on gut feeling and hand waving. This does not mean that you need to pass this judgment to HR as a label to put on that person's file. These are entirely separate things.

I have a mixed opinion on the matter of explicit grading and measuring, I would want to explore if it can be done effectively. But this PR is not about that.

**Comment by nirth** [comment]
Hm, than I'm confused how would I apply this gradation. I.e. - If you imagine that we have 50 FyDs, when would be the case that we are using it? I can see this being used if I was running talent agency, that came in a company, graded people, and decided on who to fire and who to promote - this could be a metric for developers (then adjustments metric needed for other types of people). But I don't see how would i apply this grade.

Also why are we employing Ok people in the first place? And our hiring strategy has holes if Ok people were interviews, passed, hired, and survived through 2-4 weeks of probation. I think we have to use gradation system like that - multiple steps before got very-very fucked up :)  Effectively I'm questioning context of this gradation. I think if we had it I would still simplify it, and try to fit existing _Principal_, _Senior_, _Mid-weight_, _Junior_. 

Do I make sense?

**Comment by alexykot** [comment]
I see very well how I would apply this grading, but my use case is very different from yours. I'm coming from a small company environment where many people of different backgrounds are involved in hiring process and where there is no dedicated HR function. And so I intendedly made this grading entirely skillset and role agnostic, this is solely about the personality and culture. 

So the use case is the following. 
Imagine we are building our first delivery team in the startup company. It's a crossfunctional team - with PO, UI, UX, FE, BE, everyone needed, and ideally all high grade. Also the company is very small scale, e.g. less than 10 people now, and you're aiming to create a team of about 10 people, doubling company size. How would you get CTO, Head of Design and CEO aligned on what `Good` looks like and what's the difference from `Okay` and `Great`? 

This is where this sort of definitions is highly useful because it gives everyone in a crossfunctional team a common idea.

**Comment by alexykot** [comment]
> why are we employing Ok people in the first place
I don't say we should employ them. But having a detailed idea of what Okay looks like and what's the difference from Good is needed to tell the two apart.

**Comment by nirth** [comment]
I'm a bit stupid here, but I still lack the understanding of the context, and how can it be utilised. I think we'd have to add a few more axes/dimensions, for example:

>Can lead the team and can follow good leadership. Sees the bigger 
> picture,
That's not universal statement, there are some people who see `bigger` picture everywhere, but majority see it in a specific domains or approaches.

> and can reflect back on how those details affect the whole.
Same, I wouldn't say it defines a _Great_. It's a tag, which can be applied, you can have great specialists without this skills. I think in order to make it more applicable to people, it needs to have few dimensions such as:

Quality of Work within a Domain
Quality of Work within a Toolset (technology, design)
Scale of Empathy
Ability to learn from past experience
Ability to think slow and strategicallyy
Ability to think fast and on a feet
Ability to consume and apply knowledge (or maybe even further - Time from learning to application?)

Than we could rate people in individual scale, and see it, but I'd rather use a dice :)

**Comment by alexykot** [comment]
Hmm, can we separate the context and applicability discussion from the "what is and isn't Great" discussion?

**Pull request closed without merging**
